name: flyrics
description: Spotify Lyrics for Mac
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_redux: ^0.6.0
  redux_epics: ^0.14.0
  redux_logging: ^0.4.0
  palette_generator: ^0.2.3
  http: ^0.12.2
  shimmer: ^1.1.1
  stream_transform: ^1.2.0
  flutter_dotenv: ^2.1.0
  html: ^0.14.0+3
  flutter_html: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
