name: flyrics
description: Spotify Lyrics for Mac
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_redux: ^0.6.0
  redux_epics: ^0.14.0
  redux_logging: ^0.4.0
  palette_generator: ^0.2.3
  http: ^0.12.2
  shimmer: ^1.1.1
  stream_transform: ^1.2.0
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
