name: flyrics
description: Spotify Lyrics for Mac
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^2.1.0
  flutter_hooks: ^0.13.2
  flutter_i18n: ^0.19.1
  flutter_redux: ^0.6.0
  flutter_redux_hooks: ^0.1.1
  flutter_svg: ^0.18.1
  get_it: ^4.0.4
  html: ^0.14.0+3
  http: ^0.12.2
  mockito: ^4.1.1
  palette_generator: ^0.2.3
  redux_epics: ^0.14.0
  shimmer: ^1.1.1
  stream_transform: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  test: ^1.15.3

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/genius.svg
    - assets/i18n/en.json
