version: 2.1

commands:
  prepare:
    description: "Prepare project"
    steps:
      - checkout
      - run:
          name: Create .env
          command: touch .env

jobs:
  analyze:
    docker:
      - image: cirrusci/flutter:dev
    steps:
      - prepare
      - run:
          name: Run analyze
          command: flutter analyze
  test:
    docker:
      - image: cirrusci/flutter:dev
    steps:
      - prepare
      - run:
          name: Run tests
          command: flutter test
workflows:
  cicd:
    jobs:
      - test
      - analyze
