version: 2.1

commands:
  prepare:
    description: "Prepare project"
    steps:
      - checkout
      - run:
          name: Create .env
          command: touch .env

jobs:
  analyze:
    docker:
      - image: cirrusci/flutter:dev
    steps:
      - prepare
      - run:
          name: Run analyze
          command: flutter analyze
  test:
    docker:
      - image: cirrusci/flutter:dev
    steps:
      - prepare
      - run:
          name: Run tests
          command: flutter test
  build:
    docker:
      - image: cirrusci/flutter:dev
    steps:
      - prepare
      - run: flutter config --enable-macos-desktop
      - run:
          name: Build app
          command: flutter build macos

workflows:
  cicd:
    jobs:
      - test
      - analyze
      - build:
          requires:
            - test
            - analyze
