version: 2
jobs:
  analyze:
    docker:
      - image: cirrusci/flutter:dev
    steps:
      - checkout
      - run:
          name: Run analyze
          command: flutter analyze
  test:
    docker:
      - image: cirrusci/flutter:dev
    steps:
      - checkout
      - run:
          name: Run tests
          command: flutter test

workflows:
  version: 2
  ci:
    jobs:
      - test
      - analyze
