version: 2.1

commands:
  prepare:
    description: "Prepare project"
    steps:
      - checkout
      - run:
          name: Create .env
          command: touch .env

jobs:
  analyze:
    docker:
      - image: cirrusci/flutter:dev
    steps:
      - prepare
      - run:
          name: Run analyze
          command: flutter analyze
  test:
    docker:
      - image: cirrusci/flutter:dev
    steps:
      - prepare
      - run:
          name: Run tests
          command: flutter test
  build:
    macos:
      xcode: 11.3.0
    steps:
      - prepare
      - run: git clone https://github.com/flutter/flutter.git
      - run: echo "PATH='$PATH:/home/developer/flutter/bin'" >> $BASH_ENV
      - run: flutter doctor

workflows:
  cicd:
    jobs:
      - test
      - analyze
      - build:
#          requires:
#            - test
#            - analyze
