name: Build

on:
  push:
    branches:
      - 'dev'
      - 'master'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache flutter
        id: cache-flutter
        uses: actions/cache@v2
        with:
          path: flutter
          key: ${{ runner.os }}-flutter
          restore-keys: |
            ${{ runner.os }}-flutter-
            ${{ runner.os }}-

      - name: Clone flutter source "dev"
        if: steps.cache-flutter.outputs.cache-hit != 'true'
        run: git clone https://github.com/flutter/flutter.git -b dev --depth 1
      - name: Set flutten in $PATH
        run: echo "::set-env name=PATH::$PATH:`pwd`/flutter/bin"
      - name: Enable macos desktop support
        run: flutter config --enable-macos-desktop
      - name: Install dependencies
        run: flutter pub get
      - name: Prepare .env
        run: touch .env
      - name: Build app for macOS
        run: flutter build macos
      - name: Upload build to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macos
          path: build/macos/Build/Products
