name: Build

on:
  push:
    branches:
      - 'dev'
      - 'master'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup flutter
        run: bash scripts/setup_flutter.sh
      - name: Build app for macOS
        run: flutter build macos
      - name: Upload build to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macos
          path: build/macos/Build/Products
