name: Build

on:
  push:
    branches:
      - 'dev'
      - 'master'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup flutter
        run: bash scripts/setup_flutter.sh
      - name: Enable macos desktop support
        run: flutter config --enable-macos-desktop
      - name: Build app for macOS
        run: flutter build macos --obfuscate --split-debug-info=lib/
      - name: Fix executable
        run: codesign --deep --force --verbose --sign DAACE11D8B14861874DFBA07854372C6A4E3E425 build/macos/Build/Products/Release/flyrics.app
      - name: Upload build to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macos
          path: build/macos/Build/Products/Release
