name: CI/CD

on: push

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.3.2
        with:
          channel: 'dev'
      - run: touch .env
      - run: flutter pub get
      - name: Run analyze
        run: flutter analyze
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.3.2
        with:
          channel: 'dev'
      - run: touch .env
      - run: flutter pub get
      - name: Run tests
        run: flutter test
  build:
    runs-on: macos-latest
#    needs: [analyze, test]
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.3.2
          with:
            channel: 'dev'
      - name: Enable macos desktop support
        run: flutter config --enable-macos-desktop
      - name: Install dependencies
        run: flutter pub get
      - name: Prepare .env
        run: touch .env
      - run: flutter build macos
      - name: Upload build to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macos
          path: build/macos/Build/Products
