name: CI/CD

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: git clone https://github.com/flutter/flutter.git -b stable --depth 1
      - run: export PATH="$PATH:`pwd`/flutter/bin"
#      - run: flutter precache
      - run: flutter doctor
