name: CI/CD

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: git clone https://github.com/flutter/flutter.git
      - run: export PATH="$PATH:/home/developer/flutter/bin"
      - run: flutter doctor
