name: CI/CD

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache flutter
        id: cache-flutter
        uses: actions/cache@v2
        with:
          path: flutter
          key: ${{ runner.os }}-flutter

      - name: Clone flutter source "dev"
        if: steps.cache-flutter.outputs.cache-hit != 'true'
        run: git clone https://github.com/flutter/flutter.git -b dev --depth 1
      - run: echo "::set-env name=PATH::$PATH:`pwd`/flutter/bin"
      - run: flutter config --enable-macos-desktop
      - run: flutter pub get
      - run: flutter build macos
