name: CI

on: push

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.3.2
        with:
          channel: 'dev'
      - name: Prepare .env
        run: touch .env
      - name: Install dependencies
        run: flutter pub get
      - name: Run analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test
