name: CI/CD

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: git clone https://github.com/flutter/flutter.git -b dev --depth 1
      - name: Cache paths
        uses: actions/cache@v2
        with:
          path: flutter
          key: flutter-ce40de69b7b4f89c66d19c8dbd3bd86ae30f1bc6
      - run: echo "::set-env name=PATH::$PATH:`pwd`/flutter/bin"
      - run: flutter config --enable-macos-desktop
      - run: flutter pub get
      - run: flutter build macos
